In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import tensorflow as tf
import numpy as np

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/kgf_dialogues.txt.txt')
df.head(5)

  powerful people create powerful empires
0         gold changes the destiny of men
1           fear rules the world of power
2    a man with courage can rule kingdoms
3     gold mines create kings and enemies
4           power comes to those who dare

In [10]:
df = df['powerful people create powerful empires']

In [ ]:
df

    powerful people create powerful empires
0           gold changes the destiny of men
1             fear rules the world of power
2      a man with courage can rule kingdoms
3       gold mines create kings and enemies
4             power comes to those who dare
..                                      ...
216                   fear destroys enemies
217                    gold creates legends
218                  history favors courage
219                dreams inspire greatness
220                    power builds empires

[221 rows x 1 columns]

In [12]:
movie_name = df.iloc[2:5].to_list()

In [13]:
movie_name

['a man with courage can rule kingdoms',
 'gold mines create kings and enemies',
 'power comes to those who dare']

In [14]:
movie_name

['a man with courage can rule kingdoms',
 'gold mines create kings and enemies',
 'power comes to those who dare']

In [15]:
tokenizer = tf.keras.preprocessing.text.Tokenizer()
tokenizer.fit_on_texts(movie_name)
seq = tokenizer.texts_to_sequences(movie_name)

In [16]:
seq[:10]

[[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13], [14, 15, 16, 17, 18, 19]]

In [17]:
tokenizer.word_index

{'a': 1,
 'man': 2,
 'with': 3,
 'courage': 4,
 'can': 5,
 'rule': 6,
 'kingdoms': 7,
 'gold': 8,
 'mines': 9,
 'create': 10,
 'kings': 11,
 'and': 12,
 'enemies': 13,
 'power': 14,
 'comes': 15,
 'to': 16,
 'those': 17,
 'who': 18,
 'dare': 19}

In [18]:
X = []
y = []
total_words_dropped = 0

for i in seq:
    if len(i) > 1:
        for index in range(1, len(i)):
            X.append(i[:index])
            y.append(i[index])
    else:
        total_words_dropped += 1

print("Total Single Words Dropped are:", total_words_dropped)

Total Single Words Dropped are: 0

In [19]:
X[:5]

[[1], [1, 2], [1, 2, 3], [1, 2, 3, 4], [1, 2, 3, 4, 5]]

In [20]:
y[:8]

[2, 3, 4, 5, 6, 7, 9, 10]

In [21]:
X = tf.keras.preprocessing.sequence.pad_sequences(X)

In [22]:
X

array([[ 0,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  1,  2],
       [ 0,  0,  0,  1,  2,  3],
       [ 0,  0,  1,  2,  3,  4],
       [ 0,  1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5,  6],
       [ 0,  0,  0,  0,  0,  8],
       [ 0,  0,  0,  0,  8,  9],
       [ 0,  0,  0,  8,  9, 10],
       [ 0,  0,  8,  9, 10, 11],
       [ 0,  8,  9, 10, 11, 12],
       [ 0,  0,  0,  0,  0, 14],
       [ 0,  0,  0,  0, 14, 15],
       [ 0,  0,  0, 14, 15, 16],
       [ 0,  0, 14, 15, 16, 17],
       [ 0, 14, 15, 16, 17, 18]], dtype=int32)

In [23]:
X.shape

(16, 6)

In [24]:
y = tf.keras.utils.to_categorical(y)

In [25]:
y

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.]])

In [26]:
y.shape

(16, 20)

In [27]:
vocab_size = len(tokenizer.word_index) + 1

In [37]:
vocab_size

20

In [51]:
max_sequence_len = X.shape[1]
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, 10),
    tf.keras.layers.LSTM(100, return_sequences=True),
    tf.keras.layers.LSTM(100),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(vocab_size, activation='softmax'),
])

In [50]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_6 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_7 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [40]:
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy'])

In [41]:
model.fit(X, y, epochs=60)

Epoch 1/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.0000e+00 - loss: 2.9963
Epoch 2/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - accuracy: 0.0625 - loss: 2.9938
Epoch 3/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.0625 - loss: 2.9918
Epoch 4/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.0625 - loss: 2.9897
Epoch 5/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.0625 - loss: 2.9873
Epoch 6/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.0625 - loss: 2.9845
Epoch 7/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.0625 - loss: 2.9812
Epoch 8/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.0625 - loss: 2.9775
Epoch 9/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 0.0625 - loss: 2.9729
Epoch 10/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.0625 - loss: 2.9675
Epoch 11/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.0625 - loss: 2.9610
Epoch 12/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 0.0625 - loss: 2.9533
Epoch 13/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 0.0625 - loss: 2.9440
Epoch 14/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.0625 - loss: 2.9330
Epoch 15/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.0625 - loss: 2.9200
Epoch 16/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - accuracy: 0.0625 - loss: 2.9048
Epoch 17/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.0625 - loss: 2.8879
Epoch 18/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.0625 - loss: 2.8699
Epoch 19/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.0625 - loss: 2.8523
Epoch 20/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.0625 - loss: 2.8360
Epoch 21/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.0625 - loss: 2.8200
Epoch 22/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.0625 - loss: 2.8018
Epoch 23/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - accuracy: 0.0625 - loss: 2.7797
Epoch 24/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.0625 - loss: 2.7533
Epoch 25/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.1250 - loss: 2.7250
Epoch 26/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.0625 - loss: 2.6962
Epoch 27/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.0625 - loss: 2.6689
Epoch 28/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.0625 - loss: 2.6413
Epoch 29/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.0625 - loss: 2.6127
Epoch 30/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.0625 - loss: 2.5814
Epoch 31/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.1875 - loss: 2.5478
Epoch 32/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.1875 - loss: 2.5123
Epoch 33/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.1875 - loss: 2.4745
Epoch 34/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.1875 - loss: 2.4306
Epoch 35/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.1875 - loss: 2.3827
Epoch 36/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.3125 - loss: 2.3289
Epoch 37/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.3125 - loss: 2.2708
Epoch 38/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.3125 - loss: 2.2049
Epoch 39/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.3750 - loss: 2.1393
Epoch 40/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.4375 - loss: 2.0727
Epoch 41/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.4375 - loss: 2.0053
Epoch 42/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.4375 - loss: 1.9353
Epoch 43/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 1.8670
Epoch 44/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6250 - loss: 1.8005
Epoch 45/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 1.7333
Epoch 46/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5625 - loss: 1.6668
Epoch 47/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5625 - loss: 1.6088
Epoch 48/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6250 - loss: 1.5629
Epoch 49/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5625 - loss: 1.5139
Epoch 50/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6875 - loss: 1.4403
Epoch 51/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.6875 - loss: 1.3999
Epoch 52/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6250 - loss: 1.3412
Epoch 53/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6875 - loss: 1.2839
Epoch 54/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.6875 - loss: 1.2422
Epoch 55/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.7500 - loss: 1.1892
Epoch 56/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.7500 - loss: 1.1395
Epoch 57/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.6875 - loss: 1.1065
Epoch 58/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.8125 - loss: 1.0591
Epoch 59/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8125 - loss: 1.0140
Epoch 60/60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.6875 - loss: 0.9818

In [42]:
model.save('nwp.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [43]:
import os
print("Current working directory:", os.getcwd())

Current working directory: /content

In [45]:
vocab_array = np.array(list(tokenizer.word_index.keys()))

In [46]:
vocab_array

array(['a', 'man', 'with', 'courage', 'can', 'rule', 'kingdoms', 'gold',
       'mines', 'create', 'kings', 'and', 'enemies', 'power', 'comes',
       'to', 'those', 'who', 'dare'], dtype='<U8')

In [52]:
def make_prediction(text, n_words):
    for i in range(n_words):
        text_tokenize = tokenizer.texts_to_sequences([text])
        text_padded = tf.keras.preprocessing.sequence.pad_sequences(text_tokenize, maxlen=14)
        prediction = np.squeeze(np.argmax(model.predict(text_padded), axis=-1))
        prediction = str(vocab_array[prediction - 1])
        print(vocab_array[np.argsort(model.predict(text_padded)) - 1].ravel()[:-3])
        text += " " + prediction
    return text

In [53]:
make_prediction("cloudy", 10)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 865ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
['mines' 'those' 'gold' 'kings' 'create' 'power' 'rule' 'courage' 'with'
 'and' 'who' 'dare' 'enemies' 'can' 'kingdoms' 'a' 'to']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
['mines' 'those' 'gold' 'kings' 'power' 'create' 'rule' 'courage' 'with'
 'and' 'who' 'enemies' 'dare' 'kingdoms' 'can' 'a' 'to']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
['mines' 'those' 'power' 'rule' 'gold' 'create' 'kings' 'courage' 'with'
 'and' 'who' 'enemies' 'can' 'kingdoms' 'dare' 'a' 'to']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
['mines' 'rule' 'power' 'those' 'create' 'courage' 'gold' 'kings' 'with'
 'who' 'and' 'enemies' 'can' 'kingdoms' 'a' 'to' 'dare']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
['mines' 'rule' 'power' 'courage' 'those' 'create' 'with' 'gold' 'who'
 'and' 'kings' 'can' 'enemies' 'kingdoms' 'a' 'to' 'dare']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
['mines' 'rule' 'courage' 'power' 'who' 'create' 'can' 'gold' 'and'
 'those' 'with' 'enemies' 'kingdoms' 'kings' 'a' 'man' 'to']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
['courage' 'rule' 'mines' 'can' 'power' 'who' 'and' 'gold' 'create'
 'kingdoms' 'enemies' 'with' 'those' 'man' 'kings' 'a' 'to']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
['courage' 'rule' 'can' 'mines' 'and' 'kingdoms' 'who' 'gold' 'create'
 'power' 'enemies' 'man' 'with' 'those' 'kings' 'a' 'to']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
['courage' 'can' 'rule' 'and' 'kingdoms' 'mines' 'gold' 'create' 'man'
 'who' 'enemies' 'power' 'those' 'with' 'a' 'to' 'dare']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
['courage' 'and' 'can' 'kingdoms' 'rule' 'mines' 'create' 'man' 'gold'
 'enemies' 'who' 'power' 'to' 'a' 'dare' 'those' 'with']

'cloudy comes comes comes comes comes comes comes comes comes comes'

In [54]:
make_prediction("mars", 10)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
['mines' 'those' 'gold' 'kings' 'create' 'power' 'rule' 'courage' 'with'
 'and' 'who' 'dare' 'enemies' 'can' 'kingdoms' 'a' 'to']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
['mines' 'those' 'gold' 'kings' 'power' 'create' 'rule' 'courage' 'with'
 'and' 'who' 'enemies' 'dare' 'kingdoms' 'can' 'a' 'to']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step
['mines' 'those' 'power' 'rule' 'gold' 'create' 'kings' 'courage' 'with'
 'and' 'who' 'enemies' 'can' 'kingdoms' 'dare' 'a' 'to']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
['mines' 'rule' 'power' 'those' 'create' 'courage' 'gold' 'kings' 'with'
 'who' 'and' 'enemies' 'can' 'kingdoms' 'a' 'to' 'dare']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
['mines' 'rule' 'power' 'courage' 'those' 'create' 'with' 'gold' 'who'
 'and' 'kings' 'can' 'enemies' 'kingdoms' 'a' 'to' 'dare']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
['mines' 'rule' 'courage' 'power' 'who' 'create' 'can' 'gold' 'and'
 'those' 'with' 'enemies' 'kingdoms' 'kings' 'a' 'man' 'to']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
['courage' 'rule' 'mines' 'can' 'power' 'who' 'and' 'gold' 'create'
 'kingdoms' 'enemies' 'with' 'those' 'man' 'kings' 'a' 'to']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
['courage' 'rule' 'can' 'mines' 'and' 'kingdoms' 'who' 'gold' 'create'
 'power' 'enemies' 'man' 'with' 'those' 'kings' 'a' 'to']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
['courage' 'can' 'rule' 'and' 'kingdoms' 'mines' 'gold' 'create' 'man'
 'who' 'enemies' 'power' 'those' 'with' 'a' 'to' 'dare']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
['courage' 'and' 'can' 'kingdoms' 'rule' 'mines' 'create' 'man' 'gold'
 'enemies' 'who' 'power' 'to' 'a' 'dare' 'those' 'with']

'mars comes comes comes comes comes comes comes comes comes comes'